# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Giuseppe Silvi
tagline:          'Electroacoustic Musician'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com

author:
  name:           'Giuseppe Silvi'
  url:            https://twitter.com/giuseppesilvi

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde