# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Giuseppe
tagline:          'Electroacoustic Musician'
description:      'Electroacoustic Musician'
url:              http://www.giuseppesilvi.com
baseurl:          /

author:
  name:           'Giuseppe Silvi'
  url:            https://twitter.com/giuseppesilvi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde