# Dependencies
markdown:         redcarpet
pygments:         true
    auto:		  true

# Permalinks
permalink:        pretty

# Setup
title:            Giuseppe
tagline:          'Electroacoustic Musician'
description:      'Electroacoustic Musician'
url:              http://giuseppesilvi.com

author:
  name:           'Giuseppe Silvi'
  url:            https://twitter.com/giuseppesilvi

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
  
# ftp
ftp_host:         'giuseppesilvi.com'
ftp_dir:          'www.giuseppesilvi.co'
ftp_passive:      false